version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 8010:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - app-network

networks:
  app-network:
    external: true