apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14-alpine
        imagePullPolicy: Never
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: postgres  # Replace with your desired password
        # Optionally set the POSTGRES_DB and POSTGRES_USER if needed
        - name: POSTGRES_DB
          value: postgres  # Replace with your desired database name
        - name: POSTGRES_USER
          value: postgres  # Replace with your desired username